values: !import values.yml
models_inputs: !import models_inputs.yml
logging: !import logging.yml

grid_last_period:
  (): src.commands.walk_forward_optuna_grid_command.WalkForwardOptunaGridCommand
  trainer:
    (): src.trainers.walk_forward_optuna_grid_trainer.WalkForwardOptunaGridSearchTrainer
    dataloader: cfg://values.local_dataloader
    locations: cfg://values.locations
    backtest_inputs: cfg://values.backtest_inputs
    start_dates: cfg://values.start_date
    n_trials: 200
  result_folder: !path ../results/local
  each: true

grid_six_periods:
  (): src.commands.walk_forward_optuna_grid_command.WalkForwardOptunaGridCommand
  trainer:
    (): src.trainers.walk_forward_optuna_grid_trainer.WalkForwardOptunaGridSearchTrainer
    dataloader: cfg://values.local_dataloader
    locations: cfg://values.locations
    backtest_inputs: cfg://values.backtest_inputs
    start_dates: cfg://values.start_dates
    n_trials: 200
  result_folder: !path ../results/local

best_models_each_location_paths: ['best_models/bioule/model.pkl',
                                  'best_models/les_barthes/model.pkl',
                                  'best_models/saint_felix/model.pkl',
                                  'best_models/saint_porquier/model.pkl',
                                  'best_models/tarsac/model.pkl',
                                  'best_models/verniolles/model.pkl'
                                  ]

train_local:
  (): src.commands.train_command.TrainCommand
  trainer:
    (): src.trainers.local_trainer.LocalTrainer
    models_paths: cfg://best_models_each_location_paths
    dataloader: cfg://values.local_dataloader
  result_folder: cfg://values.local_results_path
  n_predict_points: 100

predict:
  (): src.commands.predict_command.PredictCommand
  model_paths: cfg://best_models_each_location_paths
  dataloader: cfg://values.local_dataloader
  result_folder: cfg://values.local_results_path
  n_predict_points: cfg://values.n_predictions
